// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: menu/v1/menu.proto

package menuv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_menu_v1_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_menu_v1_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_menu_v1_menu_proto_rawDescGZIP(), []int{0}
}

func (x *Menu) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Menu) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type GetAllMenusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMenusRequest) Reset() {
	*x = GetAllMenusRequest{}
	mi := &file_menu_v1_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMenusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMenusRequest) ProtoMessage() {}

func (x *GetAllMenusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_v1_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMenusRequest.ProtoReflect.Descriptor instead.
func (*GetAllMenusRequest) Descriptor() ([]byte, []int) {
	return file_menu_v1_menu_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllMenusRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllMenusRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAllMenusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Menu                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMenusResponse) Reset() {
	*x = GetAllMenusResponse{}
	mi := &file_menu_v1_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMenusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMenusResponse) ProtoMessage() {}

func (x *GetAllMenusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_v1_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMenusResponse.ProtoReflect.Descriptor instead.
func (*GetAllMenusResponse) Descriptor() ([]byte, []int) {
	return file_menu_v1_menu_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllMenusResponse) GetItems() []*Menu {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_menu_v1_menu_proto protoreflect.FileDescriptor

const file_menu_v1_menu_proto_rawDesc = "" +
	"\n" +
	"\x12menu/v1/menu.proto\x12\amenu.v1\"d\n" +
	"\x04Menu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\"B\n" +
	"\x12GetAllMenusRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\":\n" +
	"\x13GetAllMenusResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.menu.v1.MenuR\x05items2Y\n" +
	"\vMenuService\x12J\n" +
	"\vGetAllMenus\x12\x1b.menu.v1.GetAllMenusRequest\x1a\x1c.menu.v1.GetAllMenusResponse\"\x00BKZIgithub.com/defvova/go_projects/mini_food_delivery/menu/pkg/menu/v1;menuv1b\x06proto3"

var (
	file_menu_v1_menu_proto_rawDescOnce sync.Once
	file_menu_v1_menu_proto_rawDescData []byte
)

func file_menu_v1_menu_proto_rawDescGZIP() []byte {
	file_menu_v1_menu_proto_rawDescOnce.Do(func() {
		file_menu_v1_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_menu_v1_menu_proto_rawDesc), len(file_menu_v1_menu_proto_rawDesc)))
	})
	return file_menu_v1_menu_proto_rawDescData
}

var file_menu_v1_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_menu_v1_menu_proto_goTypes = []any{
	(*Menu)(nil),                // 0: menu.v1.Menu
	(*GetAllMenusRequest)(nil),  // 1: menu.v1.GetAllMenusRequest
	(*GetAllMenusResponse)(nil), // 2: menu.v1.GetAllMenusResponse
}
var file_menu_v1_menu_proto_depIdxs = []int32{
	0, // 0: menu.v1.GetAllMenusResponse.items:type_name -> menu.v1.Menu
	1, // 1: menu.v1.MenuService.GetAllMenus:input_type -> menu.v1.GetAllMenusRequest
	2, // 2: menu.v1.MenuService.GetAllMenus:output_type -> menu.v1.GetAllMenusResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_menu_v1_menu_proto_init() }
func file_menu_v1_menu_proto_init() {
	if File_menu_v1_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_menu_v1_menu_proto_rawDesc), len(file_menu_v1_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menu_v1_menu_proto_goTypes,
		DependencyIndexes: file_menu_v1_menu_proto_depIdxs,
		MessageInfos:      file_menu_v1_menu_proto_msgTypes,
	}.Build()
	File_menu_v1_menu_proto = out.File
	file_menu_v1_menu_proto_goTypes = nil
	file_menu_v1_menu_proto_depIdxs = nil
}
