// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64
	MenuID    int64
	Name      string
	Position  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Menu struct {
	ID          int64
	Name        string
	Description pgtype.Text
	Active      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MenuItem struct {
	ID          int64
	CategoryID  int64
	Name        string
	Description pgtype.Text
	ImageUrl    pgtype.Text
	Available   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MenuItemPrice struct {
	ID         int64
	MenuItemID int64
	PriceCents int32
	Currency   string
	ValidFrom  time.Time
	ValidTo    *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
