// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: menuitem/v1/menuitem.proto

package menuitemv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MenuItemService_GetAllMenuItemsWithPrice_FullMethodName = "/menuitem.v1.MenuItemService/GetAllMenuItemsWithPrice"
)

// MenuItemServiceClient is the client API for MenuItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MenuItemServiceClient interface {
	GetAllMenuItemsWithPrice(ctx context.Context, in *GetAllMenuItemsWithPriceRequest, opts ...grpc.CallOption) (*GetAllMenuItemsWithPriceResponse, error)
}

type menuItemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMenuItemServiceClient(cc grpc.ClientConnInterface) MenuItemServiceClient {
	return &menuItemServiceClient{cc}
}

func (c *menuItemServiceClient) GetAllMenuItemsWithPrice(ctx context.Context, in *GetAllMenuItemsWithPriceRequest, opts ...grpc.CallOption) (*GetAllMenuItemsWithPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMenuItemsWithPriceResponse)
	err := c.cc.Invoke(ctx, MenuItemService_GetAllMenuItemsWithPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MenuItemServiceServer is the server API for MenuItemService service.
// All implementations must embed UnimplementedMenuItemServiceServer
// for forward compatibility.
type MenuItemServiceServer interface {
	GetAllMenuItemsWithPrice(context.Context, *GetAllMenuItemsWithPriceRequest) (*GetAllMenuItemsWithPriceResponse, error)
	mustEmbedUnimplementedMenuItemServiceServer()
}

// UnimplementedMenuItemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMenuItemServiceServer struct{}

func (UnimplementedMenuItemServiceServer) GetAllMenuItemsWithPrice(context.Context, *GetAllMenuItemsWithPriceRequest) (*GetAllMenuItemsWithPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllMenuItemsWithPrice not implemented")
}
func (UnimplementedMenuItemServiceServer) mustEmbedUnimplementedMenuItemServiceServer() {}
func (UnimplementedMenuItemServiceServer) testEmbeddedByValue()                         {}

// UnsafeMenuItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MenuItemServiceServer will
// result in compilation errors.
type UnsafeMenuItemServiceServer interface {
	mustEmbedUnimplementedMenuItemServiceServer()
}

func RegisterMenuItemServiceServer(s grpc.ServiceRegistrar, srv MenuItemServiceServer) {
	// If the following call panics, it indicates UnimplementedMenuItemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MenuItemService_ServiceDesc, srv)
}

func _MenuItemService_GetAllMenuItemsWithPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMenuItemsWithPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuItemServiceServer).GetAllMenuItemsWithPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuItemService_GetAllMenuItemsWithPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuItemServiceServer).GetAllMenuItemsWithPrice(ctx, req.(*GetAllMenuItemsWithPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MenuItemService_ServiceDesc is the grpc.ServiceDesc for MenuItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MenuItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "menuitem.v1.MenuItemService",
	HandlerType: (*MenuItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllMenuItemsWithPrice",
			Handler:    _MenuItemService_GetAllMenuItemsWithPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "menuitem/v1/menuitem.proto",
}
