// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: menuitem/v1/menuitem.proto

package menuitemv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_menuitem_v1_menuitem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_menuitem_v1_menuitem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_menuitem_v1_menuitem_proto_rawDescGZIP(), []int{0}
}

func (x *MenuItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MenuItem) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type GetAllMenuItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMenuItemsRequest) Reset() {
	*x = GetAllMenuItemsRequest{}
	mi := &file_menuitem_v1_menuitem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMenuItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMenuItemsRequest) ProtoMessage() {}

func (x *GetAllMenuItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menuitem_v1_menuitem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMenuItemsRequest.ProtoReflect.Descriptor instead.
func (*GetAllMenuItemsRequest) Descriptor() ([]byte, []int) {
	return file_menuitem_v1_menuitem_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllMenuItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllMenuItemsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetAllMenuItemsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type GetAllMenuItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMenuItemsResponse) Reset() {
	*x = GetAllMenuItemsResponse{}
	mi := &file_menuitem_v1_menuitem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMenuItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMenuItemsResponse) ProtoMessage() {}

func (x *GetAllMenuItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menuitem_v1_menuitem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMenuItemsResponse.ProtoReflect.Descriptor instead.
func (*GetAllMenuItemsResponse) Descriptor() ([]byte, []int) {
	return file_menuitem_v1_menuitem_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllMenuItemsResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_menuitem_v1_menuitem_proto protoreflect.FileDescriptor

const file_menuitem_v1_menuitem_proto_rawDesc = "" +
	"\n" +
	"\x1amenuitem/v1/menuitem.proto\x12\vmenuitem.v1\"\x8b\x01\n" +
	"\bMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\"g\n" +
	"\x16GetAllMenuItemsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\"F\n" +
	"\x17GetAllMenuItemsResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.menuitem.v1.MenuItemR\x05items2q\n" +
	"\x0fMenuItemService\x12^\n" +
	"\x0fGetAllMenuItems\x12#.menuitem.v1.GetAllMenuItemsRequest\x1a$.menuitem.v1.GetAllMenuItemsResponse\"\x00BSZQgithub.com/defvova/go_projects/mini_food_delivery/menu/pkg/menuitem/v1;menuitemv1b\x06proto3"

var (
	file_menuitem_v1_menuitem_proto_rawDescOnce sync.Once
	file_menuitem_v1_menuitem_proto_rawDescData []byte
)

func file_menuitem_v1_menuitem_proto_rawDescGZIP() []byte {
	file_menuitem_v1_menuitem_proto_rawDescOnce.Do(func() {
		file_menuitem_v1_menuitem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_menuitem_v1_menuitem_proto_rawDesc), len(file_menuitem_v1_menuitem_proto_rawDesc)))
	})
	return file_menuitem_v1_menuitem_proto_rawDescData
}

var file_menuitem_v1_menuitem_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_menuitem_v1_menuitem_proto_goTypes = []any{
	(*MenuItem)(nil),                // 0: menuitem.v1.MenuItem
	(*GetAllMenuItemsRequest)(nil),  // 1: menuitem.v1.GetAllMenuItemsRequest
	(*GetAllMenuItemsResponse)(nil), // 2: menuitem.v1.GetAllMenuItemsResponse
}
var file_menuitem_v1_menuitem_proto_depIdxs = []int32{
	0, // 0: menuitem.v1.GetAllMenuItemsResponse.items:type_name -> menuitem.v1.MenuItem
	1, // 1: menuitem.v1.MenuItemService.GetAllMenuItems:input_type -> menuitem.v1.GetAllMenuItemsRequest
	2, // 2: menuitem.v1.MenuItemService.GetAllMenuItems:output_type -> menuitem.v1.GetAllMenuItemsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_menuitem_v1_menuitem_proto_init() }
func file_menuitem_v1_menuitem_proto_init() {
	if File_menuitem_v1_menuitem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_menuitem_v1_menuitem_proto_rawDesc), len(file_menuitem_v1_menuitem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menuitem_v1_menuitem_proto_goTypes,
		DependencyIndexes: file_menuitem_v1_menuitem_proto_depIdxs,
		MessageInfos:      file_menuitem_v1_menuitem_proto_msgTypes,
	}.Build()
	File_menuitem_v1_menuitem_proto = out.File
	file_menuitem_v1_menuitem_proto_goTypes = nil
	file_menuitem_v1_menuitem_proto_depIdxs = nil
}
