// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Category struct {
	ID        int64     `json:"id"`
	MenuID    int64     `json:"menuId"`
	Name      *string   `json:"name,omitempty"`
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"createdAt"`
}

type Menu struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Active      bool      `json:"active"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Query struct {
}
