// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Redirect struct {
	ID        int64
	UserID    int64
	Url       string
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	ID        int64
	ExpiresAt time.Time
	UserID    int64
	TokenHash []byte
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
