// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const createRedirect = `-- name: CreateRedirect :one
INSERT INTO redirects (
    url, user_id, token
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, url, token, created_at, updated_at
`

type CreateRedirectParams struct {
	Url    string
	UserID int64
	Token  string
}

func (q *Queries) CreateRedirect(ctx context.Context, arg CreateRedirectParams) (Redirect, error) {
	row := q.db.QueryRow(ctx, createRedirect, arg.Url, arg.UserID, arg.Token)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    expires_at, user_id, token_hash
) VALUES (
    $1, $2, $3
)
`

type CreateSessionParams struct {
	ExpiresAt time.Time
	UserID    int64
	TokenHash []byte
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.ExpiresAt, arg.UserID, arg.TokenHash)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, password_hash
) VALUES (
  $1, $2
)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRedirect = `-- name: DeleteRedirect :exec
DELETE FROM redirects
WHERE id = $1 AND user_id = $2
`

type DeleteRedirectParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteRedirect(ctx context.Context, arg DeleteRedirectParams) error {
	_, err := q.db.Exec(ctx, deleteRedirect, arg.ID, arg.UserID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getRedirectByToken = `-- name: GetRedirectByToken :one
SELECT url FROM redirects
WHERE token = $1 LIMIT 1
`

func (q *Queries) GetRedirectByToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRow(ctx, getRedirectByToken, token)
	var url string
	err := row.Scan(&url)
	return url, err
}

const getRedirects = `-- name: GetRedirects :many
SELECT id, user_id, url, token, created_at, updated_at FROM redirects
WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) GetRedirects(ctx context.Context, userID int64) ([]Redirect, error) {
	rows, err := q.db.Query(ctx, getRedirects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Redirect
	for rows.Next() {
		var i Redirect
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT user_id, expires_at FROM sessions
WHERE token_hash = $1 LIMIT 1
`

type GetSessionRow struct {
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(&i.UserID, &i.ExpiresAt)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users set email = $2, password_hash = $3
WHERE id = $1
`

type UpdateUserParams struct {
	ID           int64
	Email        string
	PasswordHash string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.ID, arg.Email, arg.PasswordHash)
	return err
}
