// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: menuitemprice/v1/menuitemprice.proto

package menuitempricev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuItemPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceCents    int32                  `protobuf:"varint,2,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItemPrice) Reset() {
	*x = MenuItemPrice{}
	mi := &file_menuitemprice_v1_menuitemprice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemPrice) ProtoMessage() {}

func (x *MenuItemPrice) ProtoReflect() protoreflect.Message {
	mi := &file_menuitemprice_v1_menuitemprice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemPrice.ProtoReflect.Descriptor instead.
func (*MenuItemPrice) Descriptor() ([]byte, []int) {
	return file_menuitemprice_v1_menuitemprice_proto_rawDescGZIP(), []int{0}
}

func (x *MenuItemPrice) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuItemPrice) GetPriceCents() int32 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *MenuItemPrice) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetAllMenuItemPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	MenuItemId    int64                  `protobuf:"varint,3,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMenuItemPricesRequest) Reset() {
	*x = GetAllMenuItemPricesRequest{}
	mi := &file_menuitemprice_v1_menuitemprice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMenuItemPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMenuItemPricesRequest) ProtoMessage() {}

func (x *GetAllMenuItemPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menuitemprice_v1_menuitemprice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMenuItemPricesRequest.ProtoReflect.Descriptor instead.
func (*GetAllMenuItemPricesRequest) Descriptor() ([]byte, []int) {
	return file_menuitemprice_v1_menuitemprice_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllMenuItemPricesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllMenuItemPricesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetAllMenuItemPricesRequest) GetMenuItemId() int64 {
	if x != nil {
		return x.MenuItemId
	}
	return 0
}

type GetAllMenuItemPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItemPrice       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMenuItemPricesResponse) Reset() {
	*x = GetAllMenuItemPricesResponse{}
	mi := &file_menuitemprice_v1_menuitemprice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMenuItemPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMenuItemPricesResponse) ProtoMessage() {}

func (x *GetAllMenuItemPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menuitemprice_v1_menuitemprice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMenuItemPricesResponse.ProtoReflect.Descriptor instead.
func (*GetAllMenuItemPricesResponse) Descriptor() ([]byte, []int) {
	return file_menuitemprice_v1_menuitemprice_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllMenuItemPricesResponse) GetItems() []*MenuItemPrice {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_menuitemprice_v1_menuitemprice_proto protoreflect.FileDescriptor

const file_menuitemprice_v1_menuitemprice_proto_rawDesc = "" +
	"\n" +
	"$menuitemprice/v1/menuitemprice.proto\x12\x10menuitemprice.v1\"\\\n" +
	"\rMenuItemPrice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vprice_cents\x18\x02 \x01(\x05R\n" +
	"priceCents\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"m\n" +
	"\x1bGetAllMenuItemPricesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12 \n" +
	"\fmenu_item_id\x18\x03 \x01(\x03R\n" +
	"menuItemId\"U\n" +
	"\x1cGetAllMenuItemPricesResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.menuitemprice.v1.MenuItemPriceR\x05items2\x8f\x01\n" +
	"\x14MenuItemPriceService\x12w\n" +
	"\x14GetAllMenuItemPrices\x12-.menuitemprice.v1.GetAllMenuItemPricesRequest\x1a..menuitemprice.v1.GetAllMenuItemPricesResponse\"\x00B]Z[github.com/defvova/go_projects/mini_food_delivery/menu/pkg/menuitemprice/v1;menuitempricev1b\x06proto3"

var (
	file_menuitemprice_v1_menuitemprice_proto_rawDescOnce sync.Once
	file_menuitemprice_v1_menuitemprice_proto_rawDescData []byte
)

func file_menuitemprice_v1_menuitemprice_proto_rawDescGZIP() []byte {
	file_menuitemprice_v1_menuitemprice_proto_rawDescOnce.Do(func() {
		file_menuitemprice_v1_menuitemprice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_menuitemprice_v1_menuitemprice_proto_rawDesc), len(file_menuitemprice_v1_menuitemprice_proto_rawDesc)))
	})
	return file_menuitemprice_v1_menuitemprice_proto_rawDescData
}

var file_menuitemprice_v1_menuitemprice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_menuitemprice_v1_menuitemprice_proto_goTypes = []any{
	(*MenuItemPrice)(nil),                // 0: menuitemprice.v1.MenuItemPrice
	(*GetAllMenuItemPricesRequest)(nil),  // 1: menuitemprice.v1.GetAllMenuItemPricesRequest
	(*GetAllMenuItemPricesResponse)(nil), // 2: menuitemprice.v1.GetAllMenuItemPricesResponse
}
var file_menuitemprice_v1_menuitemprice_proto_depIdxs = []int32{
	0, // 0: menuitemprice.v1.GetAllMenuItemPricesResponse.items:type_name -> menuitemprice.v1.MenuItemPrice
	1, // 1: menuitemprice.v1.MenuItemPriceService.GetAllMenuItemPrices:input_type -> menuitemprice.v1.GetAllMenuItemPricesRequest
	2, // 2: menuitemprice.v1.MenuItemPriceService.GetAllMenuItemPrices:output_type -> menuitemprice.v1.GetAllMenuItemPricesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_menuitemprice_v1_menuitemprice_proto_init() }
func file_menuitemprice_v1_menuitemprice_proto_init() {
	if File_menuitemprice_v1_menuitemprice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_menuitemprice_v1_menuitemprice_proto_rawDesc), len(file_menuitemprice_v1_menuitemprice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menuitemprice_v1_menuitemprice_proto_goTypes,
		DependencyIndexes: file_menuitemprice_v1_menuitemprice_proto_depIdxs,
		MessageInfos:      file_menuitemprice_v1_menuitemprice_proto_msgTypes,
	}.Build()
	File_menuitemprice_v1_menuitemprice_proto = out.File
	file_menuitemprice_v1_menuitemprice_proto_goTypes = nil
	file_menuitemprice_v1_menuitemprice_proto_depIdxs = nil
}
