// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: menuitemprice/v1/menuitemprice.proto

package menuitempricev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MenuItemPriceService_GetAllMenuItemPrices_FullMethodName = "/menuitemprice.v1.MenuItemPriceService/GetAllMenuItemPrices"
)

// MenuItemPriceServiceClient is the client API for MenuItemPriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MenuItemPriceServiceClient interface {
	GetAllMenuItemPrices(ctx context.Context, in *GetAllMenuItemPricesRequest, opts ...grpc.CallOption) (*GetAllMenuItemPricesResponse, error)
}

type menuItemPriceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMenuItemPriceServiceClient(cc grpc.ClientConnInterface) MenuItemPriceServiceClient {
	return &menuItemPriceServiceClient{cc}
}

func (c *menuItemPriceServiceClient) GetAllMenuItemPrices(ctx context.Context, in *GetAllMenuItemPricesRequest, opts ...grpc.CallOption) (*GetAllMenuItemPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMenuItemPricesResponse)
	err := c.cc.Invoke(ctx, MenuItemPriceService_GetAllMenuItemPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MenuItemPriceServiceServer is the server API for MenuItemPriceService service.
// All implementations must embed UnimplementedMenuItemPriceServiceServer
// for forward compatibility.
type MenuItemPriceServiceServer interface {
	GetAllMenuItemPrices(context.Context, *GetAllMenuItemPricesRequest) (*GetAllMenuItemPricesResponse, error)
	mustEmbedUnimplementedMenuItemPriceServiceServer()
}

// UnimplementedMenuItemPriceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMenuItemPriceServiceServer struct{}

func (UnimplementedMenuItemPriceServiceServer) GetAllMenuItemPrices(context.Context, *GetAllMenuItemPricesRequest) (*GetAllMenuItemPricesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllMenuItemPrices not implemented")
}
func (UnimplementedMenuItemPriceServiceServer) mustEmbedUnimplementedMenuItemPriceServiceServer() {}
func (UnimplementedMenuItemPriceServiceServer) testEmbeddedByValue()                              {}

// UnsafeMenuItemPriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MenuItemPriceServiceServer will
// result in compilation errors.
type UnsafeMenuItemPriceServiceServer interface {
	mustEmbedUnimplementedMenuItemPriceServiceServer()
}

func RegisterMenuItemPriceServiceServer(s grpc.ServiceRegistrar, srv MenuItemPriceServiceServer) {
	// If the following call panics, it indicates UnimplementedMenuItemPriceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MenuItemPriceService_ServiceDesc, srv)
}

func _MenuItemPriceService_GetAllMenuItemPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMenuItemPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuItemPriceServiceServer).GetAllMenuItemPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuItemPriceService_GetAllMenuItemPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuItemPriceServiceServer).GetAllMenuItemPrices(ctx, req.(*GetAllMenuItemPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MenuItemPriceService_ServiceDesc is the grpc.ServiceDesc for MenuItemPriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MenuItemPriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "menuitemprice.v1.MenuItemPriceService",
	HandlerType: (*MenuItemPriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllMenuItemPrices",
			Handler:    _MenuItemPriceService_GetAllMenuItemPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "menuitemprice/v1/menuitemprice.proto",
}
