package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/defvova/go_projects/mini_food_delivery/gateway/graph/model"
)

// MenuItems is the resolver for the menuItems field.
func (r *queryResolver) MenuItems(ctx context.Context, categoryID int64) ([]*model.MenuItem, error) {
	return r.MenuItemService.GetAllMenuItemsWithPrice(ctx, categoryID)
}
