// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: category/v1/category.proto

package categoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	MenuId        int64                  `protobuf:"varint,4,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_category_v1_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Category) GetMenuId() int64 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *Category) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetAllCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	MenuId        int64                  `protobuf:"varint,3,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCategoriesRequest) Reset() {
	*x = GetAllCategoriesRequest{}
	mi := &file_category_v1_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCategoriesRequest) ProtoMessage() {}

func (x *GetAllCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetAllCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllCategoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllCategoriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetAllCategoriesRequest) GetMenuId() int64 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

type GetAllCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Category            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCategoriesResponse) Reset() {
	*x = GetAllCategoriesResponse{}
	mi := &file_category_v1_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCategoriesResponse) ProtoMessage() {}

func (x *GetAllCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetAllCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllCategoriesResponse) GetItems() []*Category {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_category_v1_category_proto protoreflect.FileDescriptor

const file_category_v1_category_proto_rawDesc = "" +
	"\n" +
	"\x1acategory/v1/category.proto\x12\vcategory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\x12\x17\n" +
	"\amenu_id\x18\x04 \x01(\x03R\x06menuId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"`\n" +
	"\x17GetAllCategoriesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x17\n" +
	"\amenu_id\x18\x03 \x01(\x03R\x06menuId\"G\n" +
	"\x18GetAllCategoriesResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.category.v1.CategoryR\x05items2t\n" +
	"\x0fCategoryService\x12a\n" +
	"\x10GetAllCategories\x12$.category.v1.GetAllCategoriesRequest\x1a%.category.v1.GetAllCategoriesResponse\"\x00BSZQgithub.com/defvova/go_projects/mini_food_delivery/menu/pkg/category/v1;categoryv1b\x06proto3"

var (
	file_category_v1_category_proto_rawDescOnce sync.Once
	file_category_v1_category_proto_rawDescData []byte
)

func file_category_v1_category_proto_rawDescGZIP() []byte {
	file_category_v1_category_proto_rawDescOnce.Do(func() {
		file_category_v1_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_v1_category_proto_rawDesc), len(file_category_v1_category_proto_rawDesc)))
	})
	return file_category_v1_category_proto_rawDescData
}

var file_category_v1_category_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_category_v1_category_proto_goTypes = []any{
	(*Category)(nil),                 // 0: category.v1.Category
	(*GetAllCategoriesRequest)(nil),  // 1: category.v1.GetAllCategoriesRequest
	(*GetAllCategoriesResponse)(nil), // 2: category.v1.GetAllCategoriesResponse
	(*timestamppb.Timestamp)(nil),    // 3: google.protobuf.Timestamp
}
var file_category_v1_category_proto_depIdxs = []int32{
	3, // 0: category.v1.Category.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: category.v1.GetAllCategoriesResponse.items:type_name -> category.v1.Category
	1, // 2: category.v1.CategoryService.GetAllCategories:input_type -> category.v1.GetAllCategoriesRequest
	2, // 3: category.v1.CategoryService.GetAllCategories:output_type -> category.v1.GetAllCategoriesResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_category_v1_category_proto_init() }
func file_category_v1_category_proto_init() {
	if File_category_v1_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_v1_category_proto_rawDesc), len(file_category_v1_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_v1_category_proto_goTypes,
		DependencyIndexes: file_category_v1_category_proto_depIdxs,
		MessageInfos:      file_category_v1_category_proto_msgTypes,
	}.Build()
	File_category_v1_category_proto = out.File
	file_category_v1_category_proto_goTypes = nil
	file_category_v1_category_proto_depIdxs = nil
}
